import sqlite3
conn=sqlite3.connect("Studentdatabase.db")
cur=conn.cursor()
#fname = input('Enter Fname= ')
#lname = input('enter lname')
#branch = input('enter branch')
#sem=input('enter sem')
#admno=input('enter adm')
#pa=input('enter pa')
#presadd=input('enter pre')
#gpa=input('enter cgpa')
#roll=input('enter roll')
#dob=input('enter dob')
#doj=input('enter doj')
#cur.execute("INSERT INTO STUDENTS(FNAME,LNAME, BRANCH, SEMESTER, ADMNO, PERMANANTADD,CGPA, CLASSROLL,DOB,DOJ )VALUES(?, ?,?,?,?,?,?,?,?,?);",  (fname, lname,  branch,  sem,  admno,  pa,  cgpa,  roll,  dob,  doj)) 
#cur.execute("UPDATE STUDENTS SET FNAME=? WHERE ADMNO=?", (fname, admno))
cur.execute("SELECT * FROM STUDENTS;")
for column in cur.fetchall():
    print(column)
conn.commit()
conn.close()
print(conn)
